import { randomUUID } from 'expo-crypto';

import { newId } from '@/utils/crypto';

jest.mock('expo-crypto', () => ({
    randomUUID: jest.fn(),
}));

const mockedRandomUUID = jest.mocked(randomUUID);

describe('newId', () => {
    test('returns a UUID generated by Expo Crypto', () => {
        mockedRandomUUID.mockReturnValue('123e4567-e89b-12d3-a456-426614174000');
        expect(newId()).toBe('123e4567-e89b-12d3-a456-426614174000');
        expect(mockedRandomUUID).toHaveBeenCalledTimes(1);
    });
});
